### ISSUE TITLE
兄弟，能不能把源码放上啊

### ISSUE THREAD

**Issue by sunbinghonter** [WanManito/mxflow.io#1]
你这放一堆压缩后的没什么意义啊

**Comment by WanManito** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WanManito/mxflow.io"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月6日(星期四) 下午5:31
收件人:&nbsp;"WanManito/mxflow.io"<mxflow.io@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[WanManito/mxflow.io] 兄弟，能不能把源码放上啊 (#1)





 
你这放一堆压缩后的没什么意义啊
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

不好意思，暂时不能开放源码，根据官方例子集成很简单的
